const manitLocations = [
  {
    id: "main-building",
    name: "Main Building",
    coordinates: [23.2156, 77.4067],
    description: "Administrative block and main offices",
    category: "academic",
  },
  {
    id: "computer-science",
    name: "Computer Science Department",
    coordinates: [23.2158, 77.4069],
    description: "Department of Computer Science and Engineering",
    category: "academic",
  },
  {
    id: "central-library",
    name: "Central Library",
    coordinates: [23.2157, 77.4068],
    description: "Main library and reading halls",
    category: "facility",
  },
  {
    id: "mechanical",
    name: "Mechanical Department",
    coordinates: [23.2155, 77.4065],
    description: "Department of Mechanical Engineering",
    category: "academic",
  },
  {
    id: "electrical",
    name: "Electrical Department",
    coordinates: [23.2154, 77.4066],
    description: "Department of Electrical Engineering",
    category: "academic",
  },
  {
    id: "hostel-1",
    name: "Boys Hostel 1",
    coordinates: [23.216, 77.407],
    description: "First year boys accommodation",
    category: "hostel",
  },
  {
    id: "jawahar-chowk",
    name: "Jawahar Chowk",
    coordinates: [23.231776, 77.394171],
    description: "Department of Computer Science and Engineering",
    category: "academic",
  },
  {
    id: "radhapuram",
    name: "Radhapuram Bus Stand",
    coordinates: [23.12268, 77.49866],
    description: "Department of Computer Science and Engineering",
    category: "academic",
  },
];
